test = {   'name': 'q1c',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> average(1)\n1.0',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> average(3)\n2.0',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> average(8)\n4.0',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> average(0)\n3.0',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
