test = {   'name': 'q1',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> X_train.shape\n(455, 13)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> X_test.shape\n(51, 13)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> Y_train.shape\n(455,)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> Y_test.shape\n(51,)',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
